# Generated by Django 3.1.2 on 2021-02-20 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store_settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=store_settings.models.get_image_path)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
