# Generated by Django 3.1.2 on 2021-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_sales', models.IntegerField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_visitors', models.IntegerField(blank=True, null=True)),
                ('new_customers', models.IntegerField(blank=True, null=True)),
                ('all_customers', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
