# Generated by Django 2.2.3 on 2019-07-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(blank=True, max_length=2000)),
                ('supplier_id', models.CharField(blank=True, max_length=255)),
                ('category_id', models.CharField(blank=True, max_length=255)),
                ('quantity_per_unit', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('unit_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('units_in_stock', models.IntegerField()),
                ('units_on_order', models.IntegerField(blank=True)),
                ('product_availible', models.BooleanField(default=False)),
                ('discount_availible', models.BooleanField(default=False)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
