# Generated by Django 2.2.3 on 2019-08-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190802_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
    ]
