# Generated by Django 2.2.3 on 2019-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='units_in_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='units_on_order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
