export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SELECT_ALL_PRODUCTS = "SELECT_ALL_PRODUCTS";
export const HANDLE_PRODUCT_SELECT = "HANDLE_PRODUCT_SELECT";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";