export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SET_EDIT_PRODUCT_ID = "SET_EDIT_PRODUCT_ID"
export const SELECT_ALL_PRODUCTS = "SELECT_ALL_PRODUCTS";
export const HANDLE_PRODUCT_SELECT = "HANDLE_PRODUCT_SELECT";
export const RESET_REDIRECT = "RESET_REDIRECT";

// Filtering Products
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const FILTER_ASCENDING = "FILTER_ASCENDING";
export const FILTER_DESCENDING = "FILTER_DESCENDING";
export const FILTER_PRICE = "FILTER_PRICE";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_UNITS = "FILTER_UNITS";

//Category
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";

// Product Pictures
export const UPDATE_PICTURES = "UPDATE_PICTURES"
export const ADD_IMAGE_TO_PRODUCT = "ADD_IMAGE_TO_PRODUCT"
export const SET_SAVED_PICTURES = "SET_SAVED_PICTURES"
export const GET_ALL_PRODUCT_IMAGES = "GET_ALL_PRODUCT_IMAGES"

//Sales
export const GET_ALL_SALES = "GET_ALL_SALES"

// Filtering Sales
export const FILTER_SALES = "FILTER_SALES";
export const FILTER_ASCENDING_SALES = "FILTER_ASCENDING_SALES";
export const FILTER_DESCENDING_SALES = "FILTER_DESCENDING_SALES";
export const FILTER_PRICE_SALES = "FILTER_PRICE_SALES";
export const FILTER_DATE_SALES = "FILTER_DATE_SALES";
export const FILTER_QUANTITY_SALES = "FILTER_QUANTITY_SALES";

// Editing Pictures
export const UPDATE_EDIT_PICTURES = "UPDATE_EDIT_PICTURES";
export const UPDATE_EDIT_DISPLAY_PICTURES = "UPDATE_EDIT_DISPLAY_PICTURES";
export const UPDATE_EDIT_NEW_PICTURES = "UPDATE_NEW_DISPLAY_PICTURES";
export const EDIT_MODE_SELECT = "EDIT_MODE_SELECT";
export const DELETE_PRODUCT_IMAGE = "DELETE_PRODUCT_IMAGE";

// Dashboard
export const GET_DASHBOARD_STATISTICS = "GET_DASHBOARD_STATISTICS";
