export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SELECT_ALL_PRODUCTS = "SELECT_ALL_PRODUCTS";
export const HANDLE_PRODUCT_SELECT = "HANDLE_PRODUCT_SELECT";

// Filtering Products
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const FILTER_ASCENDING = "FILTER_ASCENDING";
export const FILTER_DESCENDING = "FILTER_DESCENDING";
export const FILTER_PRICE = "FILTER_PRICE";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_UNITS = "FILTER_UNITS";

//Category
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";